/*
 * generated by Xtext 2.12.0
 */
package fire.ui;

import com.google.inject.Injector;
import fire.ui.internal.FireActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FireExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FireActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FireActivator.getInstance().getInjector(FireActivator.FIRE_FIRE);
	}
	
}
