/*
 * generated by Xtext 2.12.0
 */
package fire.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFireScopeProvider extends DelegatingScopeProvider {
}
