package fire.llvm;

public enum LinkageTypes {
	EXTERNAL_LINKAGE,
	AVAILABLE_EXTERNALLY_LINKAGE,
	LINK_ONCE_ANY_LINKAGE,
	LINK_ONCE_ODR_LINKAGE,
	WEAK_ANY_LINKAGE,
	WEAK_ODR_LINKAGE,
	APPENDING_LINKAGE,
	INTERNAL_LINKAGE,
	PRIVATE_LINKAGE,
	EXTERNAL_WEAK_LINKAGE,
	COMMON_LINKAGE
}