/**
 * generated by Xtext 2.10.0
 */
package fire.fire;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Id Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fire.fire.IdExpression#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see fire.fire.FirePackage#getIdExpression()
 * @model
 * @generated
 */
public interface IdExpression extends Expression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' reference.
   * @see #setValue(IdElement)
   * @see fire.fire.FirePackage#getIdExpression_Value()
   * @model
   * @generated
   */
  IdElement getValue();

  /**
   * Sets the value of the '{@link fire.fire.IdExpression#getValue <em>Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' reference.
   * @see #getValue()
   * @generated
   */
  void setValue(IdElement value);

} // IdExpression
