/**
 * generated by Xtext 2.11.0
 */
package fire.fire;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Integer Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fire.fire.IntegerLiteral#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see fire.fire.FirePackage#getIntegerLiteral()
 * @model
 * @generated
 */
public interface IntegerLiteral extends Expression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(long)
   * @see fire.fire.FirePackage#getIntegerLiteral_Value()
   * @model
   * @generated
   */
  long getValue();

  /**
   * Sets the value of the '{@link fire.fire.IntegerLiteral#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(long value);

} // IntegerLiteral
