/**
 * generated by Xtext 2.10.0
 */
package fire.fire;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fire.fire.FirePackage#getParameter()
 * @model
 * @generated
 */
public interface Parameter extends IdElement
{
} // Parameter
