grammar fire.Fire with org.eclipse.xtext.common.Terminals

generate fire "http://www.Fire.fire"

import "http://www.eclipse.org/emf/2002/Ecore" as ecore

Program: {Program}
	'program'
		statements+=WritelnStatement*
	'end'
;

WritelnStatement:
	'writeln' '(' argument=Expression ')'
;

Expression:
	{StringLiteral} value=STRING |
	{BooleanLiteral} (value?='true' | 'false') |
	{IntegerLiteral} value=Long
;

Long returns ecore::ELong:
	INT
;