/*
 * generated by Xtext 2.10.0
 */
package fire


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class FireStandaloneSetup extends FireStandaloneSetupGenerated {

	def static void doSetup() {
		new FireStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
