/*
 * generated by Xtext 2.11.0
 */
package fire.ide

import com.google.inject.Guice
import fire.FireRuntimeModule
import fire.FireStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class FireIdeSetup extends FireStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new FireRuntimeModule, new FireIdeModule))
	}
	
}
